# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# runs tests/builds on merge to master
trigger:
  - master

# runs tests/builds on PULL REQUEST master
pr:
  - master

# determine your virtual machine image
# each time pipeline is ran, you get a fresh Linux virtual machine
# this vm is discarded after each build
# a Microsoft-hosted Linux agent in Azure pipelines have Docker pre-installed on them
pool:
  vmImage: 'Ubuntu-16.04'

# variables group
# Referencing from Azure DevOps > Pipelines > Library > "Variable Groups" tab
# these group variables can be accessed as $(variable_name)
variables:
  - group: hwsc-dev-container-vars # name of variable group file that contains docker hub user/email/image-names

# task: DownloadSecureFile@1
# download a Secure File to a temporary location on build or release agent
# Secure Files is referenced from Azure DevOps > Pipelines > Library > "Secure Files" tab
# once downloaded, the Secure File is located in $(Agent.TempDirectory) directory of Azure Pipelines Agent
# selected secure files are deleted after the build or release is finished
steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: hwscdevcontainer_pw.txt # selecting the secure file to download to a temp location on agent machine
  - script: |
      cat $(Agent.TempDirectory)/hwscdevcontainer_pw.txt | docker login -u "$(hwscDevContainerUser)" --password-stdin
      docker build --no-cache -f Dockerfile -t hwsc/$(hwscDevImageNameUserSvc):$(build.buildId) .

    displayName: 'Build Docker Image'

  - script: |
      docker tag $(hwscDevImageNameUserSvc) hwsc/$(hwscDevImageNameUserSvc):$(build.buildId)
      docker push hwsc/$(hwscDevImageNameUserSvc):$(build.buildId)

    displayName: 'Push Docker Image'
